id: AddTheme
version: 1.0.0
type: Theia plugin
name: Theme service explorer
title: Theme service explorer
description: Using the Theia theme service
icon: https://irepo/projects/WBDT/repos/softwareag-che/raw/playground/plugins/is-navigator/packagenav.png
url: https://github.com/levjason/addtheme/blob/master/addtheme.theia?raw=true
publisher: Software AG
category: Other
firstPublicationDate: "2019-03-26"